### ISSUE TITLE
DLL load failed error

### ISSUE THREAD

**Issue by joedit-cmd** [csxmli2016/DFDNet#19]
Hi, I am getting this error:

File "test_FaceDict.py", line 13, in <module>
  import cv2
  File "C:Users\User\anaconda3\envs\dfdNet\lib\site-packages\cv2\____init____.py", line 5, in <module>
    from .cv2 import *
ImportError: DLL load failed: The specified module could not be found.

Thanks.

**Comment by csxmli2016** [comment]
> Hi, I am getting this error:
> 
> File "test_FaceDict.py", line 13, in
> import cv2
> File "C:Users\User\anaconda3\envs\dfdNet\lib\site-packages\cv2__**init**__.py", line 5, in
> from .cv2 import *
> ImportError: DLL load failed: The specified module could not be found.
> 
> Thanks.

Hi, this may be caused by the wrong installation of cv2. You can refer to these two solutions: https://stackoverflow.com/questions/43184887/dll-load-failed-error-when-importing-cv2/43190144
https://stackoverflow.com/questions/52349669/dll-load-failed-when-import-cv2-opencv
I am not sure whether they can solve your problem.

**Comment by joedit-cmd** [comment]
Thanks csxmli2016. I tried a few things but ended up reinstalling everything from scratch, following bycloudump's video. I think it may have to do with cuda not installed properly. Reinstalling worked and we can consider this issue closed.

Thanks again.
