### ISSUE TITLE
Get face landmark returns "No face"

### ISSUE THREAD

**Issue by AndreasAakerberg** [csxmli2016/DFDNet#3]
I tried running the get_face_landmark.py on the supplied test images but the script returns "#########No face" for all images.

**Comment by csxmli2016** [comment]
> I tried running the get_face_landmark.py on the supplied test images but the script returns "#########No face" for all images.

Hi, this is caused by running [face_alignment](https://github.com/csxmli2016/DFDNet/blob/491afcdad24c6b94b1fd28e4346f8c7f67e60989/FaceLandmarkDetection/get_face_landmark.py#L13). Please make sure that you install [this code](https://github.com/1adrianb/face-alignment) successfully.
```bash
cd ./FaceLandmarkDetection
python setup.py install
``` 
And then 
```bash
python get_face_landmark.py
```
This works successfully in my computer. If it still does not work, please refer to the [original code](https://github.com/1adrianb/face-alignment).

**Comment by AndreasAakerberg** [comment]
Found the issue: My pytorch installation was not compiled with LAPACK. By debugging i found that i got an exception in torch.inverse(t) in the utils.py file in the FaceDetection module.
