### ISSUE TITLE
Request (Only Face Restoration)

### ISSUE THREAD

**Issue by blanuk** [csxmli2016/DFDNet#41]
Hi :)

I tried it out and and the result is awesome :)
But: i need only step 3 and 4. Means no aligment, no landmark.

How can i do that?

Thanks a lot :)

//edit: the source comes already aligned and cropped to 512x512 :) (DFL from iperov)

**Comment by csxmli2016** [comment]
> )

Hi, landmark is essential, we need it to crop the eyes, nose and mouth region for dictionary feature transformation.
As for alignment, I think you'd better use our method. Because the training data is aligned in a fixed location, other alignments will generate unpleasant results due to the inconsistent features with training data.

**Comment by blanuk** [comment]
okay, i see. thanks a lot 👍 
well, i have to take a deeper look how to use it in my workflow :)
