### ISSUE TITLE
Cropping posibilties

### ISSUE THREAD

**Issue by Lubsey1** [csxmli2016/DFDNet#8]
Hi, is it a possibility to process a face in an entire frame (1920*1080) rather than cropping and scaling it to just the face?

Thanks.

**Comment by csxmli2016** [comment]
> Hi, is it a possibility to process a face in an entire frame (1920*1080) rather than cropping and scaling it to just the face?
> 
> Thanks.

Hi, this may be a valuable topic. The simple way is to copy and paste the face results to the original entire frame with upsample scale s, which can only enhance the face region. This is what I am doing (refer to [here](https://github.com/csxmli2016/DFDNet/issues/6#issuecomment-672392265).

Another complex way to process a face in an entire frame should flexibly explore the face component in different sizes and locations in CNN. But this may be limited in our current framework due to the requirement of dictionaries in the same feature space.

**Comment by csxmli2016** [comment]
> Hi, is it a possibility to process a face in an entire frame (1920*1080) rather than cropping and scaling it to just the face?
> 
> Thanks.

Hi, I have updated a new branch. It is more flexible to handle an entire frame. The background will be enhanced in my future work.
